### ISSUE TITLE
Can't rename primary key column of related table when embedding data

### ISSUE THREAD

**Issue by manuelmarichal** [begriffs/postgrest#719] opened 2016-10-14 16:11 UTC
http://localhost:3000/employees=*,departments{idDepartment:id_department}

{
  "hint": null,
  "details": null,
  "code": "42703",
  "message": "column departments.id_department does not exist"
}

This is probably related to issue #411

**Comment by ruslantalpa** [comment] 2016-10-14 17:15
Yes, it's exactly that issue, has nothing to do with renameing

**Comment by begriffs** [comment] 2016-10-14 18:02
@manuelmarichal thanks for reporting. Closing as a duplicate of 411.

**Closed by begriffs** 2016-10-14 18:02 UTC
