### ISSUE TITLE
Inserting composite type fails

### ISSUE THREAD

**Issue by rokkie** [begriffs/postgrest#837] opened 2017-03-24 13:51 UTC
I've created the following schema:

```sql
CREATE TYPE public.material AS ENUM ('aluminium','steel');

CREATE TYPE public.cylinder AS
(
  capacity smallint,
  material public.material
);

CREATE TABLE public.dive(
    id integer NOT NULL,
    cylinder public.cylinder NOT NULL,
    CONSTRAINT pk_dive PRIMARY KEY (id)
);
```

When i try to insert a record with the following request
```http
POST /dive HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
	"id": 123,
	"cylinder": "(12,'steel')"
}
```

It fails with the following message:
```json
{
  "hint": null,
  "details": null,
  "code": "22P02",
  "message": "invalid input value for enum material: \"'steel'\""
}
```

**Comment by ruslantalpa** [comment] 2017-03-24 13:53
when you select a value of that type, how is it displayed?
i.e. when pg casts it to "text" how does it look?

try using that representation as a value

**Comment by rokkie** [comment] 2017-03-24 14:06
Ok, i feel really silly now.
I could have sworn i've tried it without quotes, which works just fine.
Thanks for pointing me in the right direction!

**Comment by russelldavies** [comment] 2017-04-04 17:10
For non-ENUM composite types there is the problem that the representation returned in a GET request is different from the representation that must be sent in a POST/PATCH/PUT request. 
Example:
```sql
CREATE TYPE mytype AS (a int, b int);
CREATE TABLE foo (id serial primary key, type mytype);
INSERT INTO foo (type) VALUES ((1,2,))
```
A GET request to `/foo` will return:
```json
[
  {
    "id": 1,
    "type": {
      "a": 1,
      "b": 2
    }
  }
]
```
However, sending this as the body of the POST request will fail:
```json
{
  "type": {
    "a": 3,
    "b": 4
  }
}
```
with the error message
```json
{
  "hint": null,
  "details": "Missing left parenthesis.",
  "code": "22P02",
  "message": "malformed record literal: \"{\"a\":3,\"b\":4}\""
}
```
and what Postgres logs:
```
ERROR:  malformed record literal: "{"a":3,"b":4}"
DETAIL:  Missing left parenthesis.
STATEMENT:  
	      WITH pg_source AS (INSERT INTO "public"."foo" ("type")SELECT "type" FROM json_populate_recordset(null:: "public"."foo" , $1) RETURNING  "public"."foo".*)
	      SELECT '' AS total_result_set, pg_catalog.count(_postgrest_t) AS page_total, ( WITH s AS (SELECT row_to_json(ss) as r from pg_source as ss  limit 1) SELECT array_agg(json_data.key || '=' || coalesce('eq.' || json_data.value, 'is.null')) FROM s, json_each_text(s.r) AS json_data), ''
	      FROM (SELECT 1 FROM pg_source) _postgrest_t 
```

Sending this as the POST body does work:
```json
{
  "type": "(3,4)"
}
```

**Comment by ruslantalpa** [comment] 2017-04-07 05:10
@russelldavies the "write" part of PostgREST is probably full of inconsistencies right now. Most of the work so far was focused on getting the "read" part right and i think we almost have it.
@begriffs This issue should be reopened and title edited. There's good info here with detailed examples.

**Comment by begriffs** [comment] 2017-07-02 02:57
It's interesting, I'm not sure how postgrest should interpret a json object like

```json
{
  "a": 1,
  "b": 2
}
```

For instance if the column called "type" was json or jsonb then that json object would be a perfect match for insertion. I'm not sure how postgrest should know that in this case a key-value object should be inserted as a tuple, with "a" coming first and "b" second.

Maybe the fault here is that it was output as a json object rather than as `"(3,4)"` -- meaning it's the "read" part of postgrest that's wrong. Our type mytype really is a tuple after all, where order matters.

Thoughts? Should we look into changing the output for this kind of value?

**Comment by russelldavies** [comment] 2017-07-02 16:25
I like the way that the the fields of the type are enumerated and returned as a JSON object rather than a tuple, even if displaying it as a tuple may be more correct. It certainly makes it a lot more semantically useful than just displaying a tuple.

The Postgres JSON creation and processing functions seems to respect field order so as long as the JSON object has the same order of keys then insertion/update will work. It's necessary for the client to preserve order but this seems reasonable.

**Comment by begriffs** [comment] 2017-07-08 16:35
> It certainly makes it a lot more semantically useful than just displaying a tuple

Order semantics are *lost* when outputting json, right? Maybe what you mean is it makes the output easier for a client to parse.

> It's necessary for the client to preserve order but this seems reasonable

Can we count on javascript client libraries to serialize json with keys in a certain order? This discussion makes it seem uncertain: https://stackoverflow.com/q/280713/2375346

**Comment by russelldavies** [comment] 2017-07-10 11:33
Good point. [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) certainly doesn't preserve the ordering:
> Properties of non-array objects are not guaranteed to be stringified in any particular order. Do not rely on ordering of properties within the same object within the stringification.

But does this matter since you can just use `json_populate_record` which reconstructs the type regardless of the order of the json keys? For example, using the composite type `mytype` defined above:
```
INSERT INTO foo (type)
VALUES (json_populate_record(null::mytype, '{"b":2,"a":1}'));
```
So order semantics are lost when outputting to json but the semantics of the type field names are preserved.

**Comment by begriffs** [comment] 2017-08-05 21:48
Interesting, I didn't know about `json_populate_record`. That may provide a way to do it, although postgrest will need to detect the situation and conditionally call that function, so it doesn't seem to be an easy fix.

**Comment by begriffs** [comment] 2017-09-30 03:48
...if anyone wants to work on this I'd accept a pull request.

**Comment by russelldavies** [comment] 2017-10-18 17:32
I'd be happy to do this but I need to get a bit more familiar with the codebase first.

**Comment by begriffs** [comment] 2017-10-18 20:30
Cool! You can even open a pull request with your initial progress and I can help you if you run into Haskell errors.

**Comment by steve-chavez** [comment] 2018-01-26 00:25
Can't reproduce @russelldavies [test case](https://github.com/begriffs/postgrest/issues/837#issuecomment-291567909) on master.

Both `{ "type": { "a": 3, "b": 4 } }` and `{ "type": "(3,4)"}` payloads succeed when POSTed.

Thought this was recently fixed(unintentionally) but even as far back as `v0.3.2.0` the test case succeeds with no error.

Seems to me that the POST in the test case was done with a lib that did some json processing, malforming the input to `[{ "type": "{ \"a\": 3, \"b\": 4 }" }]`:
```sql
INSERT INTO "foo" ("type")SELECT "type" FROM json_populate_recordset(null:: "foo" , '[{ "type": "{ \"a\": 3, \"b\": 4 }" }]') RETURNING  *;
ERROR:  22P02: malformed record literal: "{ "a": 3, "b": 4 }"
DETAIL:  Missing left parenthesis.
```

Anyway, I'll add a test for this issue and then close it.

**Comment by steve-chavez** [comment] 2018-01-26 04:03
My bad, I was running the test case on `PostgreSQL 10` and in this version the bug got fixed, this is mentioned in the [CHANGELOG](https://www.postgresql.org/docs/devel/static/release-10.html):
```
Make json_populate_record() and related functions process JSON arrays and objects recursively
```

**Closed** 2018-03-14 14:36 UTC
Labels: bug, fixed-in-postgresql
