### ISSUE TITLE
Allow customization of descriptions and examples in the OpenAPI endpoint

### ISSUE THREAD

**Issue by haolez** [begriffs/postgrest#873] opened 2017-05-09 02:45 UTC
It would be nice if the automatic OpenAPI endpoint could be customized to show descriptions and example usages of the APIs being documented.

An idea would be to use PostgreSQL comments for that.

**Comment by begriffs** [comment] 2017-05-09 03:00
Nice idea, seems to have a lot of interest.

Closing this issue though as it's a duplicate of #222

**Closed by begriffs** 2017-05-09 03:00 UTC
