### ISSUE TITLE
OverlongHeaders in Response to POSTs on views

### ISSUE THREAD

**Issue by krakrjak** [begriffs/postgrest#765] opened 2016-12-07 16:05 UTC
**TLDR;** __When performing a POST into a view the Location header in the response can be too big due to postgrest failing to determine a primary key for the view. In some instances, such as large columns or large column counts, this leads to getting OverlongHeaders in the response.

I tried to simplify the table structure to make a small example, but I think I may need to expose this level of complexity to understand what's really going on.

## document_base table

```PLpgSQL
create table document_base (
      sha256hash text not null primary key
    , mimeType   text not null default 'application/octet-stream'
    , createTime timestamptz not null default current_timestamp
    , sizeBytes  bigint not null check (sizeBytes >= 0)
);
```

## document_inclusion table

```PLpgSQL
create table document_inclusion (
      sha256hash text not null references document_base primary key
    , case_id    bigint references raw_cases
    , secrecy    secrecy_level not null default enum_first(null::secrecy_level)
    , uploader   text not null references basic_auth.users
                   on delete restrict on update cascade
                   default basic_auth.current_email()
    , native       boolean not null default true
    , ocrStatus    ocr_status         not null default enum_first(null::ocr_status)
    , category     document_category  not null default enum_first(null::document_category)
    , docStatus    document_status    not null default enum_first(null::document_status)
    , unique (sha256hash, case_id)
);
```

## audit_document_relevance table

```PLpgSQL
create table audit_document_relevance (
      sha256hash text not null references document_base
    , case_id    bigint references raw_cases
    , relevance  relevance not null default enum_first(null::relevance)
    , markAuthor text not null references basic_auth.users
                   on delete restrict on update cascade
                   default basic_auth.current_email()
    , createTime timestamptz not null default current_timestamp
);
```

## document_relevance view

```PLpgSQL
create view document_relevance as
  select distinct on (sha256hash, case_id)
    sha256hash, case_id, relevance, markAuthor, createTime
    from audit_document_relevance
    join cases              as c using (case_id)
    join document_inclusion as d using (sha256hash, case_id)
    where c.memberRole > 'unassigned' and c.secrecy >= d.secrecy
    order by sha256hash, case_id, createTime DESC;
    ;
```

## documents view

```PLpgSQL
create view documents as
  select a.uploadFileName as uploadFileName
        ,r.relevance   as relevance
        ,b.sizeBytes   as sizebytes
        ,b.mimeType    as mimeType
        ,a.case_id     as case_id
        ,a.sha256hash  as sha256hash
        ,a.pathname    as pathname
        ,a.native      as native
        ,a.ocrStatus   as ocrStatus
        ,a.category    as category
        ,a.docStatus   as docStatus
        ,a.secrecy     as document_secrecy
        ,c.secrecy     as user_secrecy
        ,c.memberRole  as memberRole
        ,a.uploader    as uploader
  from document_inclusion as a
       join cases              as c using (case_id)
       join document_base      as b using (sha256hash)
       join document_relevance as r using (sha256hash,case_id)
  where c.secrecy >= a.secrecy
  ;
```

**Comment by begriffs** [comment] 2016-12-07 16:40
You're right that it is because postgrest is failing to determine the primary keys of a view. One work-around is to set the request header `Prefer: return=minimal` to suppress the Location header.

**Comment by krakrjak** [comment] 2016-12-07 16:57
While I do not use the information from the Location header at this time or with this view, I do envision this issue being more dire if the case_id column were a `serial` column or if any other column's date were computed.

**Comment by ruslantalpa** [comment] 2016-12-07 18:29
Although the symptom of the problem is that you get a bad location header, and that is because the primary keys for the view are not detected, the root of the problem i think it is that your tables are in the public schema. The fix will come from this PR https://github.com/begriffs/postgrest/pull/761
Your immediate solution is one of the these:

- compile master branch and add the patch from that PR (it's one line)
- move your tables to a different schema

**Comment by NikolayS** [comment] 2016-12-17 01:41
For those who encountered with this and cannot (or don't want) switch to HEAD version, another quick solution can be increasing nginx buffer sizes to allow long headers.

**Comment by krakrjak** [comment] 2016-12-20 19:28
I tried going straight over to 0.4 to get ready for the release and I fell into a can of worms around the new jwt handling.

So to this specific issue I tried what @ruslantalpa suggested, with a twist. I went ahead and took my working 0.3.2.0 tag based branch and backported the one liner. From a clean clone:

```bash
git checkout -b 0.3.2.0-local v0.3.2.0
git fetch origin pull/761/head
git cherry-pick 6c55539cba29a39f6ed7789aceca1f59d3e53ca3
git mergetool # trivial fixup, kdiff3 did the heavy lifting, select C for the remaining conflict
git commit # added information about the backport
```

This worked for me. A minimal amount of columns were returned in the Location header for POST requests. This also reflected in the OPTIONS request. The other hotfix of `Prefer: return=minimal` also still works.

I went ahead and published the backport of #761 to https://github.com/krakrjak/postgrest/tree/backport_pr_761

**Comment by begriffs** [comment] 2017-01-25 06:08
Thanks for the note. I wonder if I should start a branch to continue supporting the 0.3.x series, and use your backport for a 0.3.2.1 release. I'd prefer not to (would rather continue working ahead on 0.4 things) but if it's a major pain for people it's an option. Closing this issue for now.

**Closed by begriffs** 2017-01-25 06:08 UTC

**Comment by begriffs** [comment] 2017-01-29 02:08
@krakrjak I can create a 0.3.x branch off of e842667 (the place where the v0.3.2.0 tag points). Then you can open pull requests against this branch. When you're happy with the features on this branch I can build binaries for the various platforms tag future 0.3 releases on the branch.

Sound good?

**Comment by begriffs** [comment] 2017-02-04 00:10
OK, the [0.3.x](https://github.com/begriffs/postgrest/tree/0.3.x) branch is ready for your pull request(s).
