### ISSUE TITLE
Out of memeory when sending a huge json

### ISSUE THREAD

**Issue by waghanza** [begriffs/postgrest#360] opened 2015-11-13 10:11 UTC
Hi,

I'm testing to send trought `http` several `json` streams.
Everything is find, even when sending **5767337** rows in my `json`, however when sending **656420**, I have an `out of memory` 
My running command is 
~~~sh
postgrest postgres://postgres@localhost:5432/tests --anonymous postgres --port 9000 --schema public
~~~~

There is my **table** structure

~~~
                                       Table "public.purchases"
      Column       |           Type           |                       Modifiers                        
-------------------+--------------------------+--------------------------------------------------------
 id                | integer                  | not null default nextval('purchases_id_seq'::regclass)
 identifier        | character varying        | 
 product_id        | integer                  | 
 partner_id        | integer                  | 
 amount            | double precision         | 
 outlet_id         | integer                  | 
 public_price      | double precision         | 
 paid_price        | double precision         | 
 quantity          | integer                  | 
 created_at        | timestamp with time zone | 
 validity_ended_at | timestamp with time zone | 
Indexes:
    "purchases_pkey" PRIMARY KEY, btree (id)
    "index_purchases_on_outlet_id" btree (outlet_id)
    "index_purchases_on_partner_id" btree (partner_id)
    "index_purchases_on_product_id" btree (product_id)
Foreign-key constraints:
    "fk_rails_0d630f0bc7" FOREIGN KEY (product_id) REFERENCES products(id)
    "fk_rails_2e1910cebe" FOREIGN KEY (partner_id) REFERENCES partners(id)
    "fk_rails_5a081457e6" FOREIGN KEY (outlet_id) REFERENCES outlets(id)
~~~

A sample, of what is send :
~~~
{'ended_at': None, 'product_id': None, 'created_at': None, 'amount': None, 'shop_id': None, 'public_price': None, 'operation_id': None, 'identifier': u'1837379', 'partner_id': None, 'id': 317, 'paid_price': None, 'quantity': None}
~~~

**Comment by ruslantalpa** [comment] 2015-11-13 10:33
The numbers are
<postgrest: out of memory (requested 329252864 bytes)> when try to push some 656420 in json 
The program uses a lot more memory that the actual data size because of the lazy nature of haskell

**Comment by waghanza** [comment] 2015-11-13 12:12
effectively, with `5767337` in my `json` memory footprint climn to **50G**
after rebooting the machine the same test run OK, sending **654M** of `json` data

**Comment by ruslantalpa** [comment] 2015-11-13 12:14
so you can't replicate it anymore? what if you run it a few times in a row, is there some kind of memory leak?

**Comment by begriffs** [comment] 2015-11-15 23:47
I verified the memory problem locally with a 29mb json file, postgrest wants enormous amounts of memory. Using just a 6mb json causes the graph below. Curiously the profiler suggests the problem lies in a middleware function, [unsupportedAccept](https://github.com/begriffs/postgrest/blob/a6cfecbc2963ba288ad47117968c86de4f3d9d6d/src/PostgREST/Middleware.hs#L59-L65).

![screen shot 2015-11-15 at 3 43 34 pm](https://cloud.githubusercontent.com/assets/911911/11171873/d51f5e4e-8baf-11e5-97ff-5d79c9038ee5.png)

**Comment by ruslantalpa** [comment] 2015-11-16 00:09
that's probably because that function is calling the ones down below and creating the big stack, i still think the pronlem is in the parseRequestBody, try adding some strictness in some of the places inside it

**Comment by begriffs** [comment] 2015-11-16 00:51
That's a good intuition. Expanding the cost center stack name shows the offender is time and time again:

jstring_/object_/array_/parseRequestBody/parseRequest.parsedBody/parseRequest/app.request/app/runWithClaims/main.\/unsupportedAccept/defaultMiddle/main.middle/main

Less relevant but here's a graph of memory by type.
![screen shot 2015-11-15 at 4 26 35 pm](https://cloud.githubusercontent.com/assets/911911/11172121/d6e16bd6-8bb5-11e5-86b6-3e4f29926a78.png)

**Comment by ruslantalpa** [comment] 2015-11-17 09:30
Just some info for anyone trying to take a shot at this
after you successfully manage to [build](http://postgrest.com/install/server/#building-from-source) and run "stack test"
run the binary 
```
stack exec postgrest -- "postgres://postgrest_test@localhost:5432/postgrest_test" -p 3000 -a postgrest_anonymous -s test
```

and post the data like
```
curl -X POST -d @data.json http://localhost:3000/no_pk --header "Content-Type:application/json"
```

data.json file looks like
```
[
{"a":"hello", "b": "goodbye"},
{"a":"hello", "b": "goodbye"},
...
]
```

**Comment by ruslantalpa** [comment] 2015-11-18 08:37
To test this out i starting by creating a simple example of parsing a json file here
https://gist.github.com/ruslantalpa/92b42fdb87f0ce9a98c7
I repeated the content in pizza json to get the file size to 10M

When running this line
```
rm -f ./*.o ./tt && ghc -prof -auto-all -O2 tt.hs && ./tt +RTS -hc -p > /dev/null && hp2ps tt.hp
```

I get a 60M memory usage on 10M file.
Is this normal?
(Will add some of the functions that we use to see if it jumps even higher)

**Comment by ruslantalpa** [comment] 2015-11-18 09:22
I added a few functions from postgrest through which the data in the json flows in order to generate the query.
Although i still see 60M used on 10M file, the additional functions did not add much memory usage.
I remember that on 10M file in postgrest i was getting 2G memory usage
Maybe we can keep adding code to this file in order to reproduce the bug with this short code.

![tt](https://cloud.githubusercontent.com/assets/5537246/11237054/1a0bcc62-8de6-11e5-9c14-5c1b2cc9e002.png)

**Comment by ruslantalpa** [comment] 2015-11-18 15:00
Did a profiling on postgrest itself.
-hc says the module alocating all the memory is MAIN
then i did a -hd to see the data constructors 
```
stack exec postgrest -- "postgres://postgrest_test@localhost:5432/postgrest_test" -p 3000 -a postgrest_anonymous -s test +RTS -hd -p
```

 and i got this (notice how a lot of memory is being allocated by Hasql)
![postgrest](https://cloud.githubusercontent.com/assets/5537246/11244319/a2df3018-8e15-11e5-9262-81e48d2bb4af.png)

**Comment by ruslantalpa** [comment] 2015-11-18 15:30
I see "TemplateConverter.Parser" being at the center of it, leading me to think that you are actually looking for "?" in the sql that is being supplied.
In our case, there is no such thing, there are no parameters. 
Could we be constructing the statement in some other way to go around the parser inside Hasql?

**Comment by ruslantalpa** [comment] 2015-11-24 08:26
@waghanza this is fixed now in the https://github.com/begriffs/postgrest/releases/tag/v0.3.0.0 release

**Closed** 2015-11-27 18:16 UTC
