### ISSUE TITLE
Response header for OPTIONS method does not include 'Allow' methods

### ISSUE THREAD

**Issue by ChiliConSql** [begriffs/postgrest#610] opened 2016-05-25 18:19 UTC
When sending an OPTIONS request, the response header is missing "Allow" field as mentioned [here](http://zacstewart.com/2012/04/14/http-options-method.html):

> Minimally, the response should be a 200 OK and have an Allow header with a list of HTTP methods that may be used on this resource. As an authorized user on an API, if you were to request OPTIONS /users/me, you should receive something like...
> 
> 200 OK
> Allow: HEAD,GET,PUT,DELETE,OPTIONS

Instead, I receive this header:
```
http OPTIONS http://localhost:3001/clients
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Wed, 25 May 2016 18:03:57 GMT
Server: postgrest/0.3.1.1
Transfer-Encoding: chunked
```

**Comment by begriffs** [comment] 2016-05-26 01:29
You're totally right, and this is actually a duplicate of #96.

**Closed by begriffs** 2016-05-26 01:29 UTC
