### ISSUE TITLE
on error, hint sometimes missing, sometimes null.

### ISSUE THREAD

**Issue by daurnimator** [begriffs/postgrest#545] opened 2016-04-04 08:32 UTC
example without `hints`:

``` json
{
    "details":"no relation between users_organisation and users",
    "message":"could not find foreign keys between these entities"
}
```

**Comment by begriffs** [comment] 2016-04-04 16:24
Errors which contain hint are those which come right from the db. Those without are ones we made. We should think of hints for these situations and add them to the error messages.

**Comment by diogob** [comment] 2016-12-11 04:49
I'd say that details and hints as optional. This would make this behaviour not a bug, but something that could be enhanced in cases where a more suitable error can be devised.
I suggest we close this bug and reopen specific enhancements for messages we find appropriate.

**Comment by begriffs** [comment] 2016-12-11 05:04
Sounds good.

**Closed by begriffs** 2016-12-11 05:04 UTC
Labels: bug
