### ISSUE TITLE
Detecting changes without continuous polling?

### ISSUE THREAD

**Issue by manad777** [begriffs/postgrest#553] opened 2016-04-06 17:46 UTC
Let's say you have 2 users, user1 inserting/updating data, and user2 wanting to see the latest data. Does PostgREST offer user2 any way to do this other than polling PostgREST continuously?

**Comment by begriffs** [comment] 2016-04-06 18:04
Not yet, but this is one of the features we've had at the back of our minds. Thinking about using LISTEN/NOTIFY and triggers to notify postgrest of a change, and then sending that change to the client through web sockets. The problem is our haskell postgresql library needs to add support for LISTEN. There's a pull request open for it but has not yet been merged.

**Comment by sscarduzio** [comment] 2016-04-06 22:07
This would be a killer, killer feature.

**Comment by PierreR** [comment] 2016-04-07 09:26
Here is the reference to the PR:  https://github.com/nikita-volkov/hasql/pull/43

Unfortunately it doesn't sound like it is going to happen soon ;-)

**Comment by ruslantalpa** [comment] 2016-04-07 13:08
I would not bundle that functionality at all in postgrest.
It's a job for a different set of tools, like https://github.com/JarvusInnovations/lapidus

**Comment by nerfpops** [comment] 2016-04-26 13:40
I agree with @ruslantalpa. Security is also quite complex since you loose all checks and constraints when doing NOTIFY/LISTEN. Also, how important are the updates? Should the event be stored so that an offline consumer can get it later if it's offline? Or is it enough to simply fire and forget? Lapidus, ZeroMQ with Skeeter and PgQ seems like great ways to deal with job and message queues.

**Closed** 2016-10-03 23:56 UTC

**Comment by robertjpayne** [comment] 2017-09-27 12:25
@nerfpops I disagree, this is an extremely important feature for Postgrest because it's the only way to avoid continuous polling to detect changes in the database. Every application has it's own needs but this would be an extremely useful tool for many use cases, even if only used to avoid polling…

**Comment by ruslantalpa** [comment] 2017-09-27 13:12
Having this in postgrest is certainly not the only way and also probably not the right way to do this.
You send the changes from the database to a message queue and clients connect to it and listen for events
https://github.com/subzerocloud/pg-amqp-bridge
https://github.com/subzerocloud/postgrest-starter-kit
