### ISSUE TITLE
Support of column identifiers with "special" characters

### ISSUE THREAD

**Issue by user318** [begriffs/postgrest#462] opened 2016-01-17 13:38 UTC
I have column name "nic-hdl" in my table. When I make request to all columns (http://localhost:3000/person) - I receive answer as expected. But if I'm trying to specify this column in select (http://localhost:3000/person?select=nic-hdl), than I get an error:
HTTP/1.1 400 Bad Request
...
{"details":"unexpected \"h\" expecting \"->>\"","message":"\"failed to parse select parameter <<nic-hdl>>\" (line 1, column 4)"}

It will be good if there will be a way to quote identifiers. Postgres allows to use such identifiers by quoting them with double qoutes "".

**Comment by calebmer** [comment] 2016-01-17 18:55
PostgREST quotes all identifiers, even the ones which don't need it. The problem is with the PostgREST `select` query parser which doesn't allow the `-` character. This should be an easy fix @begriffs if you want to add the tag.

**Comment by calebmer** [comment] 2016-01-17 18:57
Here's the specific [line](https://github.com/begriffs/postgrest/blob/master/src/PostgREST/Parsers.hs#L61) which only allows letters, numbers and `_`.

**Comment by calebmer** [comment] 2016-01-21 23:29
@ruslantalpa I tried fixing this, but it requires a little more parser work that I'm not able to do. When I add `-` to the `oneOf` list on the line above, the parser captures expressions like `data-` in `data->x->y->>z`. Is there a good fix for this?

**Comment by ruslantalpa** [comment] 2016-01-22 09:28
see if this works
```
pFieldName :: Parser Text
pFieldName =  cs <$> (
     ((many1 (letter <|> digit)) `sepBy` (oneOf "_-"))
      <?> "field name (* or [a..z0..9_])"
    )
```

**Comment by SebAlbert** [comment] 2016-01-23 01:11
I think you should really try to implement quoting within the select parameter. It's only a matter of time until somebody with a comma or -> in a column name would show up...

**Comment by begriffs** [comment] 2016-04-03 18:52
Anyone want to push this over the finish line and send a PR?

**Comment by begriffs** [comment] 2016-04-25 06:45
I created a failing test to demonstrate the problem on branch `hyphenated-cols`. @ruslantalpa the suggested `pFieldName` doesn't work because it tries parsing `[String]` which `cs` can't convert to `Text`.

**Closed** 2016-05-15 07:55 UTC
Labels: bug, easy

**Comment by jotpe** [comment] 2017-10-30 22:48
@SebAlbert Good point.
I am using a mediawiki api and a key column is called *. It fails, in the select list and in the "where" list. I expected that quoting identifiers should work :(

**Comment by steve-chavez** [comment] 2018-12-10 19:35
Related to https://github.com/PostgREST/postgrest/issues/1008.
