### ISSUE TITLE
tsquery config for @@ operator

### ISSUE THREAD

**Issue by SebLours** [begriffs/postgrest#542] opened 2016-04-02 10:23 UTC
Is there a way to use another tsquery config for the `@@` operator ?
For example `simple` config.

I have a custom text search config for proper nouns (simple+unaccent) and i don't want to set this config as default one in my postgres connection.

Then, i must use the text search config in the `tsquery` function.

``` sql
select *
from racer
where ts_full_name @@ to_tsquery('proper_noun', 'query');
```

**Comment by ruslantalpa** [comment] 2017-08-26 21:00
duplicate of #601

**Closed by ruslantalpa** 2017-08-26 21:00 UTC
Labels: duplicate, enhancement
