### ISSUE TITLE
Location Header size issue

### ISSUE THREAD

**Issue by ireverent** [begriffs/postgrest#217] opened 2015-06-24 20:41 UTC
When trying to Post any large amounts of data, the automatic inclusion of the location header causes a Header_Too_Big error. Should we allow a perfer option to be sent to suppress this when dealing with datasets that are too large for be in a header?

**Comment by begriffs** [comment] 2015-06-24 21:18
* Can you provide the value of a large header (one that is not so big that it actually causes the error but which is getting pretty big)
* Is it an error issued by the Haskell server or by the consumer?
* If I recall correctly the location header should include params for only columns that are part of a primary key or else all column values if there is no primary key. Maybe you're running into the all-column situation and should define a key.

A Prefer header to disable sending back a location header is certainly a possibility. I'm curious to learn more about the issue.

**Comment by ireverent** [comment] 2015-06-24 21:32
The error is issued by the browser(chrome).  We have a define primary  key but still get the full record back in the header for some reason.  Not sure on a header getting to the sizethat is big but not large enough to cause the issue.  We are encoding pdf documents which is giving the issue when it returns the encoded string in the header.

**Comment by begriffs** [comment] 2015-06-24 22:02
Thanks for reporting the problem. What are the columns in your table, and what is the primary key like? Is it compound?

**Comment by ireverent** [comment] 2015-06-25 12:42
Here are the fields from my table:

id serial PRIMARY KEY,
  institution_id integer NOT NULL,
  training_name varchar(255) NOT NULL,
  file_data text NOT NULL,
  version_serial varchar(6) NOT NULL UNIQUE,
  date_uploaded timestamp NOT NULL DEFAULT current_timestamp,
  replaced_training_id integer,
  is_deleted boolean NOT NULL DEFAULT false

The file_data comes in as a base 64 encoded pdf string. On insert this returns a location header with all the fields including the huge string which breaks the size limit on headers.

**Comment by begriffs** [comment] 2015-08-30 21:20
@ireverent things seem fine for tables in my test db. Can you run a query to help me debug?

```sql
    select kc.column_name
      from
        information_schema.table_constraints tc,
        information_schema.key_column_usage kc
    where
      tc.constraint_type = 'PRIMARY KEY'
      and kc.table_name = tc.table_name and kc.table_schema = tc.table_schema
      and kc.constraint_name = tc.constraint_name
      and kc.table_schema = ?
      and kc.table_name  = ?
```
(filling in the question marks with schema and table names for the problem table) The results of this query determine which columns to include in the Location response header. If the query returns nothing then all columns are used.

**Comment by ireverent** [comment] 2015-08-31 12:52
Here is the result
 id


What exactly is this piece of code doing at line 168 in app.hs?

        let params = urlEncodeVars
                      $ map (\t -> (cs $ fst t, cs (paramFilter $ snd t)))
                      $ sortBy (comparing fst) $ M.toList primaries

This was spitting out all the url encoded items we sent in. Since one of those is a long base64 encoded item, we get issues with header sizes in chrome.

**Comment by ireverent** [comment] 2015-09-08 19:40
Did you have a chance to look at this? I am a little confused as to what the above code is doing. Thanks

**Comment by begriffs** [comment] 2015-09-24 03:58
The `params` variable above will be a query string. The `urlEncodeVars` takes a list of string tuples and generates a string like this:

```haskell
urlEncodeVars [("hello","world"),("airport","o'hare")]
-- generates "hello=world&airport=o%27hare"
```

We're passing it the names and of primary key columns and values which will be filters created like this

```haskell
paramFilter :: JSON.Value -> T.Text
paramFilter JSON.Null = "is.null"
paramFilter v = "eq." <> unquoted v
```

I'm more curious about the value of `primaryKeys` in your case and how it translates into `primaries`. We would expect `primaryKeys` to be `["id"]` and `primaries` to be a map with one key of `"id"` and and value of whatever the column holds. One way to learn more about the value of `primaryKeys` is to hit the route with an OPTIONS verb rather than a POST. The result should contain

```json
{
  "pkey": [
    "id"
  ],
}
```

If it contains more values in the list then we know the `primaryKeys` function is misbehaving.

**Comment by begriffs** [comment] 2015-09-24 04:25
To try to reproduce I created a table called `hell` with the fields you specified. The OPTIONS verb reports

```json
{
  "pkey": [
    "id"
  ],
  "columns": [
    {
      "references": null,
      "default": "nextval('\"1\".hell_id_seq'::regclass)",
      "precision": 32,
      "updatable": true,
      "schema": "1",
      "name": "id",
      "type": "integer",
      "maxLen": null,
      "enum": [],
      "nullable": false,
      "position": 1
    },
    {
      "references": null,
      "default": null,
      "precision": 32,
      "updatable": true,
      "schema": "1",
      "name": "institution_id",
      "type": "integer",
      "maxLen": null,
      "enum": [],
      "nullable": false,
      "position": 2
    },
    {
      "references": null,
      "default": null,
      "precision": null,
      "updatable": true,
      "schema": "1",
      "name": "training_name",
      "type": "character varying",
      "maxLen": 255,
      "enum": [],
      "nullable": false,
      "position": 3
    },
    {
      "references": null,
      "default": null,
      "precision": null,
      "updatable": true,
      "schema": "1",
      "name": "file_data",
      "type": "text",
      "maxLen": null,
      "enum": [],
      "nullable": false,
      "position": 4
    },
    {
      "references": null,
      "default": null,
      "precision": null,
      "updatable": true,
      "schema": "1",
      "name": "version_serial",
      "type": "character varying",
      "maxLen": 6,
      "enum": [],
      "nullable": false,
      "position": 5
    },
    {
      "references": null,
      "default": "now()",
      "precision": null,
      "updatable": true,
      "schema": "1",
      "name": "date_uploaded",
      "type": "timestamp without time zone",
      "maxLen": null,
      "enum": [],
      "nullable": false,
      "position": 6
    },
    {
      "references": null,
      "default": null,
      "precision": 32,
      "updatable": true,
      "schema": "1",
      "name": "replaced_training_id",
      "type": "integer",
      "maxLen": null,
      "enum": [],
      "nullable": true,
      "position": 7
    },
    {
      "references": null,
      "default": "false",
      "precision": null,
      "updatable": true,
      "schema": "1",
      "name": "is_deleted",
      "type": "boolean",
      "maxLen": null,
      "enum": [],
      "nullable": false,
      "position": 8
    }
  ]
}
```

Then I post to it with this payload:

```json
{
"id": 2,
"institution_id": 3,
"training_name": "hi",
"file_data": "foobarfoobar",
"version_serial": 4
}
```

The location header in the response is `/hell?id=eq.2`. Next I set `file_data` to be a 200k base64 encoded pdf (adjusting id and version_serial as needed for uniqueness constraints). This also responds with the correct location response header. So I'm wondering how else your database differs from mine. You probably have a foreign key constraint on `institution_id` as well but that shouldn't matter.

**Comment by ireverent** [comment] 2015-09-24 04:53
So I think I might have figured out the issue. In postgrest you can define primary key through a constraint, or through defining it on the table definition. So for example. 

CREATE TABLE orders(  
ord_no integer PRIMARY KEY,  
ord_date date,  
item_name character(35),  
item_grade character(1),  
ord_qty numeric,  
ord_amount numeric  
); 

Which is how we did it. I noticed on the auth table example a constraint was created for primary key instead of defining it on the column like above. Is there something in how postgrest gets the primary key that would prevent the kind of definition that we did? When I do the option it returns nothing in pkey.

**Comment by NikolayS** [comment] 2015-09-24 07:09
When you work with ordinary tables, it's ok – PostgREST detects primary key and put only corresponding columns to the `Location` header.

But if you work through views in `"1"` schema (as suggested in "external" tutorial in very beginning) and create simple view like `CREATE VIEW ... AS SELECT * FROM public.xxxx;` – primary key is hidden from PostgREST and it starts to include all columns to the response after `INSERT`.

I checked it for my DB, using metadata query from https://github.com/begriffs/postgrest/blob/b5e76f42a55813de8ea77104ee836e9ec48dc816/src/PostgREST/PgStructure.hs#L113.

**Comment by begriffs** [comment] 2015-09-24 17:53
Right, it does not detect the keys through a view. This will be fixed when we merge @ruslantalpa's changes which includes: https://github.com/ruslantalpa/skin/commit/04273b5d477eba825150e898ee856acdb5aebe07

**Comment by ireverent** [comment] 2015-09-24 18:02
Well it is always nice to get down to the root of a problem and see that a fix is already on it's way. Once that change and a final way of handling postgrest.auth for user manipulation are in place I will be able to run postgrest without modification.

**Comment by ruslantalpa** [comment] 2015-09-24 18:38
One interesting aspect i encountered when looking at this, it seems info about materialised views is not present in information_schema (not sure about pg_catalog) so this fix will detect fk from views but not materialised views

**Comment by ruslantalpa** [comment] 2015-09-24 18:44
i started merging my experiment into a branch of postgrest directly here https://github.com/ruslantalpa/postgrest/tree/skin the current state is 2 tests failing out or 100. Tomorrow i'll look at fixing this problem in that branch also

**Comment by ruslantalpa** [comment] 2015-09-24 20:34
Seems like an important issue to leave it until my branch is merged,
i created a fix here https://github.com/ruslantalpa/postgrest/commit/8783615ebcf06b6066230abfa8a2ad428e168d79
but i have no idea why the test is failing, when i simply build and exec the output is correct.
Anyone interested in taking a look?

**Comment by begriffs** [comment] 2015-09-25 00:56
The test fails for me too. In addition, when I use the postman rest client to request `OPTIONS http://localhost:3000/insertable_view_with_join` it responds with an empty array for `pkey` just like the test did.

**Comment by ruslantalpa** [comment] 2015-09-25 06:57
The issue is that postgrest_anonymous user does not have rights  to query (or can't see anything) information_schema.view_column_usage
try this
```
set local role 'postgrest_test';
--set local role 'postgrest_anonymous';
select * from information_schema.view_column_usage
```

not sure why this is the case, the code works is the user executing the request has access to that info

**Comment by ruslantalpa** [comment] 2015-09-25 07:33
Since in the new branch i query the info upfront, this works, https://github.com/ruslantalpa/postgrest/commit/54d1e4112a39804445c168291adca036ae708178

**Comment by ireverent** [comment] 2015-10-03 16:12
Any more testing on this?

**Closed** 2015-10-04 16:42 UTC
