### ISSUE TITLE
building from source - "function unnest(smallint[], smallint[]) does not exist" 

### ISSUE THREAD

**Issue by mrsot** [begriffs/postgrest#321] opened 2015-10-16 14:18 UTC
Hello! I am new with postgrest and I need some help with getting the API running. 

I have [built the project from source](https://github.com/begriffs/postgrest/wiki/Building-from-source) on Centos 6.7.

When trying to invoke postgrest it fails and I get the following output:
```
#postgrest --db-host localhost --db-port 5432 --db-name my_db --db-user my_user --db-pass my_pass --db-pool 200 --port 3000 --anonymous my_user
WARNING, running in insecure mode, auth will be in plaintext
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 3000
postgrest: user error (TxError (ErroneousResult "42883" "function unnest(smallint[], smallint[]) does not exist" Nothing (Just "No function matches the given name and argument types. You might need to add explicit type casts.")))
#
```

My current OS state is:
CentOS release 6.7 (Final)
PostgreSQL 9.3.10
git version 2.6.1
postgrest-0.2.11.1

I add the installation output after the "stack build":
```
# stack build
postgrest-0.2.11.1: unregistering (local file changes)
postgrest-0.2.11.1: configure
Configuring postgrest-0.2.11.1...
postgrest-0.2.11.1: build
Preprocessing library postgrest-0.2.11.1...
[ 1 of 12] Compiling PostgREST.Error  ( src/PostgREST/Error.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/PostgREST/Error.o )
[ 2 of 12] Compiling Paths_postgrest  ( .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/autogen/Paths_postgrest.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/Paths_postgrest.o )
[ 3 of 12] Compiling PostgREST.Types  ( src/PostgREST/Types.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/PostgREST/Types.o )
[ 4 of 12] Compiling PostgREST.RangeQuery ( src/PostgREST/RangeQuery.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/PostgREST/RangeQuery.o )
[ 5 of 12] Compiling PostgREST.PgQuery ( src/PostgREST/PgQuery.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/PostgREST/PgQuery.o )
[ 6 of 12] Compiling PostgREST.PgStructure ( src/PostgREST/PgStructure.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/PostgREST/PgStructure.o )
[ 7 of 12] Compiling PostgREST.QueryBuilder ( src/PostgREST/QueryBuilder.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/PostgREST/QueryBuilder.o )
[ 8 of 12] Compiling PostgREST.Parsers ( src/PostgREST/Parsers.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/PostgREST/Parsers.o )

src/PostgREST/Parsers.hs:8:1: Warning:
    The import of βData.Functorβ is redundant
      except perhaps to import instances from βData.Functorβ
    To import instances alone, use: import Data.Functor()

src/PostgREST/Parsers.hs:9:1: Warning:
    The import of βData.Traversableβ is redundant
      except perhaps to import instances from βData.Traversableβ
    To import instances alone, use: import Data.Traversable()
[ 9 of 12] Compiling PostgREST.Config ( src/PostgREST/Config.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/PostgREST/Config.o )
[10 of 12] Compiling PostgREST.Auth   ( src/PostgREST/Auth.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/PostgREST/Auth.o )
[11 of 12] Compiling PostgREST.App    ( src/PostgREST/App.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/PostgREST/App.o )
[12 of 12] Compiling PostgREST.Middleware ( src/PostgREST/Middleware.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/PostgREST/Middleware.o )
In-place registering postgrest-0.2.11.1...
Preprocessing executable 'postgrest' for postgrest-0.2.11.1...
[ 1 of 13] Compiling Paths_postgrest  ( .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/autogen/Paths_postgrest.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/Paths_postgrest.o )
[ 2 of 13] Compiling PostgREST.Config ( src/PostgREST/Config.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/PostgREST/Config.o )
[ 3 of 13] Compiling PostgREST.Error  ( src/PostgREST/Error.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/PostgREST/Error.o )
[ 4 of 13] Compiling PostgREST.Types  ( src/PostgREST/Types.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/PostgREST/Types.o )
[ 5 of 13] Compiling PostgREST.Parsers ( src/PostgREST/Parsers.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/PostgREST/Parsers.o )
[ 6 of 13] Compiling PostgREST.RangeQuery ( src/PostgREST/RangeQuery.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/PostgREST/RangeQuery.o )
[ 7 of 13] Compiling PostgREST.PgQuery ( src/PostgREST/PgQuery.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/PostgREST/PgQuery.o )
[ 8 of 13] Compiling PostgREST.QueryBuilder ( src/PostgREST/QueryBuilder.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/PostgREST/QueryBuilder.o )
[ 9 of 13] Compiling PostgREST.Auth   ( src/PostgREST/Auth.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/PostgREST/Auth.o )
[10 of 13] Compiling PostgREST.PgStructure ( src/PostgREST/PgStructure.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/PostgREST/PgStructure.o )
[11 of 13] Compiling PostgREST.App    ( src/PostgREST/App.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/PostgREST/App.o )
[12 of 13] Compiling PostgREST.Middleware ( src/PostgREST/Middleware.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/PostgREST/Middleware.o )
[13 of 13] Compiling Main             ( src/PostgREST/Main.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux-gmp4/Cabal-1.22.4.0/build/postgrest/postgrest ...
Warning: modules not listed in postgrest.cabal for 'postgrest' component (add to other-modules):
    Paths_postgrest
    PostgREST.App
    PostgREST.Auth
    PostgREST.Config
    PostgREST.Error
    PostgREST.Middleware
    PostgREST.Parsers
    PostgREST.PgQuery
    PostgREST.PgStructure
    PostgREST.QueryBuilder
    PostgREST.RangeQuery
    PostgREST.Types
postgrest-0.2.11.1: install
Installing library in
/usr/local/postgrest/.stack-work/install/x86_64-linux-gmp4/lts-3.7/7.10.2/lib/x86_64-linux-ghc-7.10.2/postgrest-0.2.11.1-1gw55jyuvQAEs2EioXsBin
Installing executable(s) in
/usr/local/postgrest/.stack-work/install/x86_64-linux-gmp4/lts-3.7/7.10.2/bin
Registering postgrest-0.2.11.1...
#
```

Can you please help me find what is wrong with my installation? 

I have also downloaded the latest binary(postgrest-0.2.11.1) and it runs with no issues but I wanted to try the filtering options which are not available yet.

Best regards!

**Comment by ruslantalpa** [comment] 2015-10-16 14:22
Does it immediately fail or when you make a request?
If after the request, what's the exact request string?

**Comment by ruslantalpa** [comment] 2015-10-16 14:25
Also, if you have a query log for postgresql, it would help if you pasted the the query that postgrest tried to run and failed.

**Comment by ruslantalpa** [comment] 2015-10-16 14:28
it will also go faster if you have time to chat here https://gitter.im/begriffs/postgrest

**Comment by mrsot** [comment] 2015-10-16 14:43
It fails immediately. I will check for any queries made by postgrest at initialization but I think that there might be some further requirements from unnest function in order to run.

**Comment by ruslantalpa** [comment] 2015-10-16 14:45
In this case, one of the queries from this file is failing
https://github.com/begriffs/postgrest/blob/master/src/PostgREST/PgStructure.hs

**Comment by ruslantalpa** [comment] 2015-10-16 14:46
What is the version of postgresql?

**Comment by jfranki** [comment] 2015-10-16 14:48
I just had the exact same error today trying to build from source for the first time. I'm running Ubuntu Server 14.04 (x64) and PostgreSQL 9.3.9.

**Comment by mrsot** [comment] 2015-10-16 14:48
Postgresql 9.3.10

**Comment by ruslantalpa** [comment] 2015-10-16 14:50
try looking at the log or try running the queries from the file i mentioned

**Comment by ruslantalpa** [comment] 2015-10-16 14:51
it's probably because we use a feature from pg 9.4, that's what i am running

**Comment by mrsot** [comment] 2015-10-16 14:58
I am currently away from my pc, but I 'll check it as soon as possible. If this is the case, does it mean I should upgrade to 9.4 or is there a workaround?

**Comment by ruslantalpa** [comment] 2015-10-16 14:58
Not necesarily, we'll try to change the query if possible to be compatible with 9.3

**Comment by mrsot** [comment] 2015-10-16 15:10
I 'll let you know soon.

**Comment by jfranki** [comment] 2015-10-16 15:25
I had never done anything with Haskell until today. Could you tell me where could I find the log or run a specific file?

**Comment by mrsot** [comment] 2015-10-16 16:13
Here is the log content from /var/lib/pgsql/9.3/data/pg_log/postgresql-Fri.log  after running postgrest command. This query is indeed causing the problem!
```
< 2015-10-16 18:31:37.042 EEST >ERROR:  function unnest(smallint[], smallint[]) does not exist at character 322
< 2015-10-16 18:31:37.043 EEST >HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
< 2015-10-16 18:31:37.043 EEST >STATEMENT:  WITH table_fk AS ( SELECT ns.nspname AS table_schema, tab.relname AS table_name, column_info.cols AS columns, other.relname AS foreign_table_name, column_info.refs AS foreign_columns FROM pg_constraint, LATERAL (SELECT array_agg(cols.attname) AS cols, array_agg(cols.attnum) AS nums, array_agg(refs.attname) AS refs FROM unnest(conkey, confkey) AS _(col, ref), LATERAL (SELECT * FROM pg_attribute WHERE attrelid = conrelid AND attnum = col) AS cols, LATERAL (SELECT * FROM pg_attribute WHERE attrelid = confrelid AND attnum = ref) AS refs) AS column_info, LATERAL (SELECT * FROM pg_namespace WHERE pg_namespace.oid = connamespace) AS ns, LATERAL (SELECT * FROM pg_class WHERE pg_class.oid = conrelid) AS tab, LATERAL (SELECT * FROM pg_class WHERE pg_class.oid = confrelid) AS other WHERE confrelid != 0 ORDER BY (conrelid, column_info.nums) ) SELECT * FROM table_fk UNION ( SELECT vcu.table_schema, vcu.view_name AS table_name, array_agg(vcu.column_name::text) AS columns, table_fk.foreign_table_name, table_fk.foreign_columns FROM information_schema.view_column_usage as vcu JOIN table_fk ON table_fk.table_schema = vcu.view_schema AND table_fk.table_name = vcu.table_name AND vcu.column_name = ANY (table_fk.columns) WHERE vcu.view_schema NOT IN ('pg_catalog', 'information_schema') AND columns = table_fk.columns GROUP BY vcu.table_schema, vcu.view_name, table_fk.foreign_table_name, table_fk.foreign_columns ) UNION ( SELECT vcu.view_schema as table_schema, table_fk.table_name, table_fk.columns, vcu.view_name as foreign_table_name, array_agg(vcu.column_name::text) as foreign_columns FROM information_schema.view_column_usage as vcu JOIN table_fk ON table_fk.table_schema = vcu.view_schema AND table_fk.foreign_table_name = vcu.table_name AND vcu.column_name = ANY (table_fk.foreign_columns) WHERE vcu.view_schema NOT IN ('pg_catalog', 'information_schema') AND foreign_columns = table_fk.foreign_columns GROUP BY vcu.view_schema, table_fk.table_name, vcu.view_name, table_fk.columns )
```

@jfranki  I am working on Centos 6.7 and found the logs in /var/lib/pgsql/9.3/data/pg_log/ .I am also new and I am not sure if this is by default or there needs to be some initial configuration in order to get them.

**Comment by ruslantalpa** [comment] 2015-10-16 21:32
the log helps, the problem is we are using "unnest", i'll see about changing that. you don't have to do anything, you compiled and executed it right.
In the mean time if you want to play with it, try installing 9.4 until we fix this query

**Comment by mrsot** [comment] 2015-10-16 21:57
ok, I 'll try installing 9.4 then! Thanks again.

**Comment by jfranki** [comment] 2015-10-19 14:53
Yup, version related. Updating from 9.3.9 to 9.4.5 solved the problem.

**Comment by LeKovr** [comment] 2015-10-24 07:18
In 9.3.9 we create stored proc:
```sql
CREATE OR REPLACE FUNCTION public.unnest(smallint[], smallint[]) 
RETURNS TABLE (f1 SMALLINT, f2 SMALLINT) 
IMMUTABLE LANGUAGE 'sql' AS $_$
  SELECT unnest($1) f1, unnest ($2) f2
$_$;
```
and this solves the problem.
Is it correct? If so, why not to use 
```
unnest($1), unnest ($2)
```
instead of
```
unnest($1, $2)
```
?

**Comment by ruslantalpa** [comment] 2015-10-24 09:55
That is beacuse i do not know pg all that well :) i'll try your suggestion and see if it will work so that we can get back to supporting 9.3

**Comment by begriffs** [comment] 2015-10-24 20:04
This fix has been merged to master. It will be in the next release.

**Closed by begriffs** 2015-10-24 20:04 UTC
