### ISSUE TITLE
Allow filtering within numeric interval

### ISSUE THREAD

**Issue by fzaninotto** [begriffs/postgrest#292] opened 2015-09-24 15:35 UTC
Hi, and thanks for your awesome work! Postgrest is really great.

If I want to perform a query with more than one condition on a single column (e.g. to search entries where column "foo" is between 0 and 10). Postgrest seems to support the following syntax, where the same query param is repeated twice:

```
GET /entries?foo=gt.1&foo=lt.10
```

However, most HTTP clients libraries use a hash for the query string, and it's not possible to set two values for the same key. As a consequence, unless I design the query string by hand, I can't perform a BETWEEN query on Postgrest.

Would it be possible to support a more usual syntax such as:

```
GET /entries?foo=['gt.1','lt.10']
```

**Comment by ruslantalpa** [comment] 2015-09-24 18:34
Interesting feature/request. I would agree it's necessary but would suggest a different format
```
/entries?1:foo=gt.1&2:foo=lt.10
```
It should be easy enough to implement.
Let's get @begriffs blessing on the format :) and i'll implement this for you tomorrow in the main branch

**Comment by begriffs** [comment] 2015-09-25 01:10
That is an interesting way to solve it. I hesitate about the numbers though. They feel kind of arbitrary: the above example could also have been written `/entries?1:foo=gt.1&568126:foo=lt.10`. The url becomes less canonical.

I can see the trouble where javascript libraries often use a hash to create url params. You could try another library to build the urls though, such as https://github.com/medialize/URI.js

```js
var URI = require('URI.js');
URI("http://example.org/foo")
  .addQuery("col", "gt.2")
  .addQuery("col", "lt.10");

/* returns
{ [String: 'http://example.org/foo?col=gt.2&col=lt.10']
  _string: 'http://example.org/foo?col=gt.2&col=lt.10',
  _parts:
   { protocol: 'http',
     username: null,
     password: null,
     hostname: 'example.org',
     urn: null,
     port: null,
     path: '/foo',
     query: 'col=gt.2&col=lt.10',
     fragment: null,
     duplicateQueryParameters: false,
     escapeQuerySpace: true },
  _deferred_build: false }
*/
```

Do you think this will work in your situation?

**Comment by ruslantalpa** [comment] 2015-09-25 03:27
Sometimes you don't have the option of changing the lib (actually most of the time :)
You are right about arbitrary, the number part would be ignorred, however i don't see a nicer/easyer way to implement this. Bu this does raise problems like the location header...

**Comment by begriffs** [comment] 2015-09-25 15:07
The location header should be OK actually since it always specifies column equality rather than inequality.

What about extending the `in` operator with interval notation? We can currently say `?col=in.a,b,c` for a discrete list of values, but we could mimic the [math notation](https://en.wikipedia.org/wiki/Interval_(mathematics)#Notations_for_intervals) and write e.g. `?col=in.[0,5)`. Strictly speaking the number prefixes you suggested are more flexible since they allow us to conjoin any  predicates on a column. I'm just wondering if the column interval constraint makes up 90% of the cases where a column would be filtered more than once.

The original example would be written
```
GET /entries?foo=in.(1,10)
```

**Comment by fzaninotto** [comment] 2015-09-25 15:16
My current problem is finding rows in an interval. So the `in.()` syntax would work fine for now. 

Someone else (or maybe me) may come back again in the future about this very problem for a non-interval query.

**Comment by ruslantalpa** [comment] 2015-09-25 16:15
So basically we agree that number prefixes are more flexible but there is the question of being canonical.
I would argue that it's not an issue.
My logic is this.
Canonical (in my understanding) means each url uniquely identifies a resource (or a set) or resources.
but if let's say your items start at id=10 then
```
/items?id=gt.2
/items?id=gt.3
``` 
return the same items (not to mention that new itms might get inserted)
So by this logic, the fact that 1:id=gt.10 is the same as 2343:id=gt.10 would not be a problem.
So the main question is, is this format actually breaking some RFC/rest convention?

**Comment by calebmer** [comment] 2015-09-25 19:11
While the proposed solution of arbitrary prefixes is interesting and
clever, it is important to remember that the proposal is a concession for a
client that does not have full support for the query parameters
specification.

We should be looking for solutions in the client and not adding a new
feature which is ideally never used and limits our choices for future
features.

@fzaninotto maybe you could give us more details as I'm sure we can find a
solution that better fits your use case.

The `in.[2,5)` syntax is pretty fun though and something that might be good
for me to implement 😊

**Comment by ruslantalpa** [comment] 2015-09-25 19:56
I would disagree that it's a concession, my gut feeling is that a lot of the js libs implement query building like @fzaninotto described. You can't realistically expect that established js libs would change to support the same parameter being supplied twice. They might even argue that &a=1&a=2 does not even make sense and it breaks a convention.
For example if you send such a qs to PHP you only get one of the values so it's kind of a convention (maybe even a RFC thing) that a query string contains a parameter only once.

**Comment by calebmer** [comment] 2015-09-26 03:08
I come from the nodejs community so I can confirm your gut feeling.
However, the nodejs core library does it the correct, compliant way,
[source](https://nodejs.org/api/querystring.html). Anything not using the
core library should be fixed, not PostgREST.

Can't speak to PHP, that was many moons ago for me 😊

At the end of the day I can get over the fact we are supporting bad
implementations if they are the majority. My biggest fear is extensibility
and maintenance in the future. Especially when this could potentially not
be an issue down the road and we get stuck supporting it.

**Comment by begriffs** [comment] 2015-09-27 06:20
#### Suggestion

* immediate term: use a workaround
  * construct or modify the query params by hand to do the filtering you need
  * or created a [stored procedure](https://github.com/begriffs/postgrest/wiki/Routing#stored-procedures) taking the parameters for the lower and upper range values
  * or created a [computed column](https://github.com/begriffs/postgrest/wiki/Advanced-Endpoints#filtering-by-computed-columns) `bar` that is just an alias for `foo` so you can say `?foo=gt.1&bar=lt.10`
* medium term: we add the interval syntax extension to `in`
* long term
    * design an alternate form for filtering which allows full propositional logic, meaning arbitrary ANDs and ORs
    * or wait and see if general double filtering even becomes a problem given the ability to filter intervals

#### Random slightly philosophical thought...

The number prefixing creates distinct yet [intensionally equal](https://en.wikipedia.org/wiki/Intension) routes, meaning they differ syntactically but cause the same operation to happen. Consider `?foo=eq.bar` and `?200:foo=eq.bar`. They both cause the same sql underneath. As @ruslantalpa mentioned above we do already have distinct URLs which are equal, but they are [*ex*tensionally equal](https://en.wikipedia.org/wiki/Extensionality). The routes `?id=gt.2` and `?id=gt.3` do the same thing but only in the case where all rows have ids greater than three. The routes produce the same results *in this case*, but they generate different sql and so are not intensionally equal. The only other violator at the moment is the ordering of query params.

**Comment by fzaninotto** [comment] 2015-09-28 07:14
In this particular case, I'm using Angular.js, which uses a JavaScript Object to store query parameters. No way to work around unless hacking into the `$http` service. Even worse, I'm using `Restangular`, which is a replacement for Angular's `$http`. Even harder to hack into that one.

I agree that number prefixing doesn't sound good to me. And I agree too that this problem is part of a larger problem (combining multiple queries with boolean logic).

**Comment by calebmer** [comment] 2015-09-28 18:39
It looks to me like Restangular supports the array syntax. [Source](
https://github.com/mgonto/restangular/blob/78b58f3ca729f3e2f6be96174e3e7a66e46b8973/src/restangular.js#L732-L742
).

And by extension Angular, from which it claims the code was copied.

**Comment by begriffs** [comment] 2015-10-05 23:07
@fzaninotto does the Restangular query param array interface take care of the problem for now?

**Comment by fzaninotto** [comment] 2015-10-06 08:13
No it doesn't. The Restangular snippet you linked to shows an iteration on the ` params` object properties. Or am I missing something?

**Comment by calebmer** [comment] 2015-10-06 10:43
@fzanintto [this](https://github.com/mgonto/restangular/blob/78b58f3ca729f3e2f6be96174e3e7a66e46b8973/src/restangular.js#L734) shows the value is always coerced into an array (even if it is a single value). [Here](https://github.com/mgonto/restangular/blob/78b58f3ca729f3e2f6be96174e3e7a66e46b8973/src/restangular.js#L736) they loop over that array. And unless I'm missing something blatantly obvious, the angular source code expects this functionality as is seen [here](https://github.com/angular/angular.js/blob/master/src/ng/http.js#L27-L41) so it would be restangular's bad for copying outdated code. Just out of curiosity, have you tried the array syntax?

Hope this helps 😊

**Comment by fzaninotto** [comment] 2015-10-06 16:32
The value that is coerced into an array is already a value on the query object. 

``` js
var query = {
  foo: 'bar' //    <= here, 'bar' is coerced to 'bar' and iterated over.
};
``` 

So the query object is a JAvaScript object and cannot contain two values for the same key.

**Comment by calebmer** [comment] 2015-10-06 16:42
Try:
```javascript
let query = {
  foo: ['bar', 'baz']
}
```

**Comment by ruslantalpa** [comment] 2016-06-01 13:36
can this particular question be solved by using this
`foo=<@.[1,10]`

the only problem to overcome is that it generates this query
```SQL
select * from projects
where id <@ '[1,10]'::unknown
```

and we need this 
```SQL
select * from projects
where id <@ '[1,10]'::int4range
```

**Comment by begriffs** [comment] 2016-06-01 20:23
That's elegant. Mind=blown. 💥 

It does seem to have trouble even with the type cast
```sql
select 'yay' where 1 @> '[1,10]'::int4range;

ERROR:  operator does not exist: integer @> int4range
LINE 1: select 'yay' where 1 @> '[1,10]'::int4range;
                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.```

**Comment by SebAlbert** [comment] 2016-06-01 20:26
It's
`select 'yay' where 1 <@ '[1,10]'::int4range;`
(the other way around, I always try to think of it as a mathematical "subset" symbol visually)

**Comment by begriffs** [comment] 2016-06-01 20:28
So it is, just what Ruslan wrote too. :)

Yeah that query worked!

**Closed** 2017-02-03 22:07 UTC
Labels: enhancement
