### ISSUE TITLE
self-reference foreign keys, can get "parent" but not "child"

### ISSUE THREAD

**Issue by BrandonChubb** [begriffs/postgrest#987] opened 2017-09-26 18:19 UTC
Refiling our problem as the last one was poorly worded to our intent (#960 which I'll close in a moment).

For reference sake, here's a FK example with 2 separate tables:
```sql
create table one (
id text not null primary key,
name text not null,
other text);

create table two (
id text not null primary key,
name text not null);

alter table only one add constraint otherptr foreign key (other)  references two(id);

insert into two values ('21', 'twenty-one');
insert into two values ('22', 'twenty-two');

insert into one values ('11', 'eleven', '21');
insert into one values ('12', 'twelve', '22');

grant all on table one to testuser;
grant all on table two to testuser;
```

Some queries:
```bash
# all parents (others) of one members
% curl 'http://localhost:3000/one?select=other(*)'
[{"other":{"id":"21","name":"twenty-one"}},{"other":{"id":"22","name":"twenty-two"}}]

# all children of two members (ones that have others pointing to two)
% curl 'http://localhost:3000/two?select=one.other(*)'
[{"one":[{"id":"11","name":"eleven","other":"21"}]},{"one":[{"id":"12","name":"twelve","other":"22"}]}]

# only 11
% curl 'http://localhost:3000/one?id=eq.11'
[{"id":"11","name":"eleven","other":"21"}]

# parent (other) of 11
% curl 'http://localhost:3000/one?id=eq.11&select=other(*)'
[{"other":{"id":"21","name":"twenty-one"}}]

# only 21
% curl 'http://localhost:3000/two?id=eq.21'
[{"id":"21","name":"twenty-one"}]

# child of 21 (that with other pointing to 21)
% curl 'http://localhost:3000/two?id=eq.21&select=one.other(*)'
[{"one":[{"id":"11","name":"eleven","other":"21"}]}]

# There was some hint you could use the FK as a qualifier, but no (not that it matters)
% curl 'http://localhost:3000/two?select=otherptr(*)'
{"message":"Could not find foreign keys between these entities, No relation found between two and otherptr"}
% curl 'http://localhost:3000/two?select=one.otherptr(*)'
{"message":"Could not find foreign keys between these entities, No relation found between two and one"}
```

Now with self-referencing FKs
Table creation...
```sql
create table family_tree (
id text not null primary key,
name text not null,
parent text);

alter table only family_tree add constraint pptr foreign key (parent) references family_tree(id);

insert into family_tree values ('1', 'Parental Unit', NULL);
insert into family_tree values ('2', 'Kid One', '1');
insert into family_tree values ('3', 'Kid Two', '1');
insert into family_tree values ('4', 'Grandkid One', '2');
insert into family_tree values ('5', 'Grandkid Two', '3');

grant all on table family_tree to testuser;
```

Now some queries against the above:
```bash
# dump of whole tree
% curl 'http://localhost:3000/family_tree'
[{"id":"1","name":"Parental Unit","parent":null},{"id":"2","name":"Kid One","parent":"1"},{"id":"3","name":"Kid Two","parent":"1"},{"id":"4","name":"Grandkid One","parent":"2"},{"id":"5","name":"Grandkid Two","parent":"3"}]

# dump "Kid Two" from middle generation
% curl 'http://localhost:3000/family_tree?id=eq.3'
[{"id":"3","name":"Kid Two","parent":"1"}]

# Get kid two parents:
% curl 'http://localhost:3000/family_tree?id=eq.3&select=parent(*)'
[{"parent":{"id":"1","name":"Parental Unit","parent":null}}]

# Get kid two kids?: (should be Grandkid Two)
% curl 'http://localhost:3000/family_tree?id=eq.3&select=family_tree.parent(*)'
[{"family_tree":[]}]   <--------- Broken case here
```

Does that all make sense?  So we think we should be able to pull in not only the entries pointed AT by the FKs, but grab the entries doing the pointing (the children in this case).  Which works with 2 tables, but not 1.

**Comment by BrandonChubb** [comment] 2017-09-28 13:30
This was CentOS7 binary version 0.4.3.0.

**Comment by begriffs** [comment] 2017-09-30 05:21
I think this is a question for @steve-chavez who has done a lot of work on the embedding logic.

**Comment by skinkie** [comment] 2017-10-01 20:55
Also subscribing to this issue. I also find myself the problem that a table only having ingress references is not able to automatically beyond the direct relation. In my case:

```
create table one(oneid text not null, primary key(oneid));
create table two(twoid text not null, primary key(twoid), oneid text references one(oneid));
create table three(threeid text not null, primary key(threeid), twoid text references two(twoid));
grant select, references on one to testuser;
grant select, references on two to testuser;
grant select, references on three to testuser;
```

```
curl -X GET "http://localhost/one?select=two(*)" -H "accept: application/json" ; echo
[]
curl -X GET "http://localhost:3000/two?select=one(*)" -H "accept: application/json" ; echo
[]
curl -X GET "http://localhost:3000/one?select=three(*)" -H "accept: application/json" ; echo
{"message":"Could not find foreign keys between these entities, No relation found between one and three"}
```

**Comment by ruslantalpa** [comment] 2017-10-02 05:47
@skinkie i don't see a reason for that to exist, it's a very niche use case and if you really need that you can use views/computed columns

PS: as i've mentioned in other issues, you are not using `&select` right, you need too include columns from both tables.
you are writing this
`http://localhost/one?select=two(*)`
but actually you are thinking of this
`http://localhost/one?select=*,two(*)`
however it's always better to write it like this
`http://localhost/one?select=oneid,two(twoid)`

**Comment by begriffs** [comment] 2017-10-27 21:54
OK I ran through the original issue again more carefully. Looks like the crux of the matter is that it's possible for a table to embed itself *through* another table, but not embed itself through *itself*.

```bash
# Embeds two inside two through one
curl 'http://localhost:3000/two?select=one.other(*)'

# Fails to embed family_tree inside family_tree through family_tree
curl 'http://localhost:3000/family_tree?select=family_tree.parent(*)'
```

This does seem like a bug, unless I'm overlooking something about how the foreign keys operate. @steve-chavez does this look like a bug to you as well?

**Comment by skinkie** [comment] 2017-10-27 22:01
Mmm... I have got the itself through itself working though (latest version).

/servicejourney?id=eq.cxx:SJ:148316-777@201712&select=*,servicejourneypattern(*),baselineid(*,servicejourneypattern(*))

```json
[
{
id: "cxx:SJ:148316-777@201712",
departuretime: "15:18:00",
departuredayoffset: 0,
servicejourneypatternrefid: "cxx:JP:67655-1-1-wnsbgr-asdbel@201712",
availabilityconditionrefid: "cxx:AC:148316@201712",
timedemandtyperefid: "cxx:TDT:148316-1-1-wnsbgr-asdbel-777@201712",
baselineid: null,
servicejourneypattern: {
id: "cxx:JP:67655-1-1-wnsbgr-asdbel@201712",
name: null,
routerefid: "cxx:RT:67655-1-1@201712",
destinationdisplayrefid: "cxx:DD:M142-asdbel@201712"
}
}
]
```

**Comment by begriffs** [comment] 2017-10-27 22:15
@skinkie interesting, can you try with @BrandonChubb's example schema and see if you get different results? There might be a clue here between the keys in your example vs those in the original.

**Comment by skinkie** [comment] 2017-11-14 12:09
@begriffs  I think I can reproduce the problem of @BrandonChubb. If I would add an extra table, I can only do so for the first level, but not the second level. 

So this would work:
/servicejourney?id=eq.cxx:SJ:148928-51@3123951-F302-171113&select=id,servicejourneypattern(*,pointsinjourneypattern(*),servicejourneypattern(*))

But this wouldn't:
/servicejourney?id=eq.cxx:SJ:148928-51@3123951-F302-171113&select=id,servicejourneypattern(*,pointsinjourneypattern(*),servicejourneypattern(*,pointsinjourneypattern(*)))

```json
{
hint: "No function matches the given name and argument types. You might need to add explicit type casts.",
details: null,
code: "42883",
message: "function row_to_json(json) does not exist"
}```

Changing * to the foreign key to the table:
/servicejourney?id=eq.cxx:SJ:148928-51@3123951-F302-171113&select=id,servicejourneypattern(*,pointsinjourneypattern(*),servicejourneypattern(baselinerefid,pointsinjourneypattern(*)))

```json
{
hint: null,
details: null,
code: "42703",
message: "column servicejourneypattern_servicejourneypattern.id does not exist"
}
```

Changing the foreign key also into the other table:
/servicejourney?id=eq.cxx:SJ:148928-51@3123951-F302-171113&select=id,servicejourneypattern(*,pointsinjourneypattern(*),servicejourneypattern(baselinerefid,pointsinjourneypattern(baselinerefid,*)))
```json
{
hint: null,
details: null,
code: "42703",
message: "column pointsinjourneypattern.baselinerefid does not exist"
}
```

**Comment by Arm1nE** [comment] 2018-01-22 18:33
@begriffs @steve-chavez I have the same problem, Is there any solution?

**Comment by Arm1nE** [comment] 2018-02-10 13:22
@begriffs @steve-chavez is there any release version based on this fixed?

**Comment by begriffs** [comment] 2018-02-10 15:55
Not yet. There's a pull request with the fix, but it has not yet been merged and hence not released.

**Closed** 2018-02-21 14:23 UTC
Labels: bug
