### ISSUE TITLE
PostgREST can't find foreign key due to a second view

### ISSUE THREAD

**Issue by alexesDev** [begriffs/postgrest#562] opened 2016-04-15 21:09 UTC
Simple schema for example

``` sql
create schema core;
create schema shop_order;
create schema api;

create table core.items (
  id serial primary key
);

create table shop_order.items (
  id serial primary key,
  item_id int not null references core.items on delete restrict,
  quantity decimal(9, 3),
  price decimal(9, 2) not null
);

create view api.shop_order_items as
  select * from shop_order.items;

create view api.core_items as
  select * from core.items;
```

Request: `http://localhost:3000/shop_order_items?select=*,item{*}`
Response: `[]`
It works. But if create a second view and if it has the column with the same name, it fails.

``` sql
create view api.sale_report as
  select i.item_id, sum(i.quantity * i.price) as total_sum
    from shop_order.items i
   group by i.item_id;
```

 Request: `http://localhost:3000/shop_order_items?select=*,item{*}`
 Response: `{"details":"no relation between shop_order_items and item",
 "message":"could not find foreign keys between these entities"}`

After rename `item_id` to something else... all works again.

``` sql
create view api.sale_report as
  select i.item_id as nitem_id, sum(i.quantity * i.price) as total_sum
    from shop_order.items i
   group by i.item_id;
```

**Comment by james-tassl** [comment] 2016-07-12 18:17
We also seem to be having this issue with our views. Using the explicit column name seems to resolve most of these issues, but today we will have to go back and adjust our code to work around this issue.

**Comment by ruslantalpa** [comment] 2016-07-12 18:51
Can you post the view definitions and the request that fails.
Remember that you can have subselects ONLY in the WHERE section of the view definition

**Comment by richardmansfield** [comment] 2017-04-28 05:09
I think I might be running into this problem too, with v0.3.2.0, 

```
CREATE SCHEMA IF NOT EXISTS a;
CREATE SCHEMA IF NOT EXISTS api_v1;

CREATE TABLE a.authors (id serial PRIMARY KEY, name text);
CREATE TABLE a.books (title text, author_id integer REFERENCES a.authors (id));
INSERT INTO a.authors (id, name) VALUES (1, 'Steinbeck');
INSERT INTO a.books (title, author_id) VALUES ('The Grapes of Wrath', 1);
CREATE VIEW api_v1."authors-1" AS (SELECT * FROM a.authors);
CREATE VIEW api_v1."books-1" AS (SELECT * FROM a.books);
CREATE VIEW api_v1."authors-2" AS (SELECT * FROM a.authors WHERE id = 1);
CREATE VIEW api_v1."books-2" AS (SELECT * FROM a.books WHERE author_id = 1);

```

Requesting `/api_v1/authors-1?select=*,books-1{*}` succeeds, but `/api_v1/authors-2?select=*,books-2{*}` fails with
`{"details":"no relation between authors-2 and books-2","message":"could not find foreign keys between these entities"}`

As far as I can tell, renaming the fk column in the second set of views isn't helping

**Comment by ruslantalpa** [comment] 2017-04-28 05:20
@richardmansfield did you restart postgrest after creating the views?

**Comment by richardmansfield** [comment] 2017-04-30 23:37
@ruslantalpa yes, I've been restarting postgrest. Second and subsequent views of the referenced (books) table containing the fk are not a problem, it seems it's just failing in the case where there is more than one view of the authors table, so:

`/api_v1/authors-1?select=*,books-1{*}` works
`/api_v1/authors-1?select=*,books-2{*}` works
`/api_v1/authors-2?select=*,books-1{*}` fails
`/api_v1/authors-2?select=*,books-2{*}` fails.

**Comment by ruslantalpa** [comment] 2017-05-01 03:45
are the table/views in the public schema? if yes, try the latest release 4.1

**Comment by ruslantalpa** [comment] 2017-08-26 20:57
this is a duplicate of #823
please reopen if not so

**Closed by ruslantalpa** 2017-08-26 20:57 UTC
Labels: duplicate
