### ISSUE TITLE
postgrest can't find foreign key on view?

### ISSUE THREAD

**Issue by daurnimator** [begriffs/postgrest#546] opened 2016-04-04 08:44 UTC
Getting the error:

```
could not find foreign keys between these entities
no relation between users_organisation and users
```

My table/view:

```
gresap=# \d+ core.users_organisation
                          Table "core.users_organisation"
    Column    |       Type       | Modifiers | Storage | Stats target | Description 
--------------+------------------+-----------+---------+--------------+-------------
 users        | uuid             | not null  | plain   |              | 
 organisation | uuid             | not null  | plain   |              | 
 member_type  | core.member_type | not null  | plain   |              | 
Indexes:
    "users_organisation_pkey" PRIMARY KEY, btree (users, organisation)
Foreign-key constraints:
    "users_organisation_organisation_fkey" FOREIGN KEY (organisation) REFERENCES core.organisation(id) ON UPDATE CASCADE ON DELETE CASCADE
    "users_organisation_users_fkey" FOREIGN KEY (users) REFERENCES core.users(id) ON UPDATE CASCADE ON DELETE CASCADE

gresap=# \d+ public.users_organisation
                  View "public.users_organisation"
    Column    |       Type       | Modifiers | Storage | Description 
--------------+------------------+-----------+---------+-------------
 users        | uuid             |           | plain   | 
 organisation | uuid             |           | plain   | 
 member_type  | core.member_type |           | plain   | 
View definition:
 SELECT b.users,
    b.organisation,
    b.member_type
   FROM ( SELECT users_organisation.organisation
           FROM core.users_organisation
          WHERE users_organisation.users = core.current_setting_no_throw('postgrest.claims.user_id'::text)::uuid) a
     JOIN core.users_organisation b ON a.organisation = b.organisation;
Triggers:
    update_users_organisation INSTEAD OF INSERT OR DELETE OR UPDATE ON users_organisation FOR EACH ROW EXECUTE PROCEDURE core.update_users_organisation()
```

I have restarted postgrest since creating the relations. (which was the issue in the similar sounding issue #447)

**Comment by ruslantalpa** [comment] 2016-04-04 09:24
the problem is in the view definition
In order for relation detection to work, you can not use subselects in FROM section,
you need to directly reference the other tables
Move the WHERE section to the top level

**Comment by daurnimator** [comment] 2016-04-05 01:04
> the problem is in the view definition
In order for relation detection to work, you can not use subselects in FROM section,
you need to directly reference the other tables
Move the WHERE section to the top level

Wouldn't that be an entirely different query though?

**Comment by daurnimator** [comment] 2016-04-05 01:23
> Wouldn't that be an entirely different query though?

I think this works though:

```diff
-	from (
-		select organisation from core.users_organisation
-		where users = core.current_setting_no_throw('postgrest.claims.user_id')::uuid
-	) as a inner join core.users_organisation as b
-		on (a.organisation = b.organisation);
+	from core.users_organisation as a inner join core.users_organisation as b
+		on (a.organisation = b.organisation
+			and a.users = core.current_setting_no_throw('postgrest.claims.user_id')::uuid);
```

**Comment by ruslantalpa** [comment] 2016-04-05 05:24
Relation detection in views has limitation, the definition of the views needs to be like in your second examples, you can't have subqueries in FROM and JOIN sections.
i.e. this is not a bug, it's expected behaviour (known limitation) :)

**Comment by daurnimator** [comment] 2016-04-05 05:44
> i.e. this is not a bug, it's expected behaviour (known limitation) :)

I guess what would be nice is a way to 'override' in cases such as this: some way to tell postgrest "for this view look at this foreign key".

**Comment by ruslantalpa** [comment] 2016-04-05 05:55
There was a discussion in #354 but that specific problem was addressed in another way so there was no need for extending the query syntax

**Comment by ruslantalpa** [comment] 2016-06-01 12:47
@daurnimator there is a plan (in my head) on how to "tell postgrest" some things but it will take some time to implement. In the meantime please close this issue (and if you like, open a new one requesting the feature to "tell postgrest about relations it can't detect")

**Comment by ruslantalpa** [comment] 2017-08-03 08:43
Closing. known limitation, possible solutions discussed in #709

**Closed by ruslantalpa** 2017-08-03 08:43 UTC
