### ISSUE TITLE
Support for recent versions of hasql?

### ISSUE THREAD

**Issue by peti** [begriffs/postgrest#127] opened 2015-01-21 17:35 UTC
Hi, we've updated to the latest version of `hasql` in NixOS, but unfortunately this means that `postgrest` won't compile any longer: http://packdeps.haskellers.com/feed?needle=postgrest. Are there any plans to release an updated version that supports the latest dependencies?

**Comment by begriffs** [comment] 2015-01-21 17:47
Yep, that'll be my top priority. I'm estimating I'll have it upgraded by Monday. In the meantime is there an adjustment for the package version constraints in the cabal file to make it build successfully with an older Hasql?

https://github.com/begriffs/postgrest/blob/master/postgrest.cabal#L23-L24

**Comment by peti** [comment] 2015-01-21 17:51
We try to avoid distributing multiple versions of the same package unless we absolutely have to, because this complicates the effort for the maintainers quite a bit. We'll just leave the build broken until the update comes out. That shouldn't be a problem since it's only for a couple of days. Thank you for the quick response!

**Comment by begriffs** [comment] 2015-01-26 18:22
@adambaker and I completed most of the rewrite yesterday. Today we'll tackle the error handling and maybe get it merged back to master.

**Comment by begriffs** [comment] 2015-01-29 05:48
Almost there but hitting a bug in the new code. It appears in a few of the tests and I'm guessing there's a root cause for all of them.

https://circleci.com/gh/begriffs/postgrest/104

The `NULL input` error looks telling. It happens when trying to map array values in a query.

https://github.com/nikita-volkov/hasql-postgres/blob/a3040131c754d3e48d9812cf5f106927fdd38af9/library/Hasql/Postgres/Mapping.hs#L75

**Closed** 2015-01-31 20:45 UTC

**Comment by peti** [comment] 2015-02-02 12:32
Will you release a new version to Hackage, too?

**Comment by begriffs** [comment] 2015-02-02 16:14
Yep, the new version (0.2.5.1) is up on hackage.
