### ISSUE TITLE
Enable GET requests on RPCs

### ISSUE THREAD

**Issue by omani** [begriffs/postgrest#935] opened 2017-08-10 20:53 UTC
Hi,
I have this case where I need GET requests on rpcs rather than POST.

I would like to call: http://localhost:3000/rpc/myfunc?param1=value1&param2=value2

any plans to implement GET requests on rpcs?

**Comment by begriffs** [comment] 2017-08-10 21:05
It was discussed in https://github.com/begriffs/postgrest/issues/328#issuecomment-162029728 for stored procs which are marked as immutable. I haven't looked at that issue for some time, so I don't recall the consensus, but have a look at it and see what you think about the proposals there.

**Comment by omani** [comment] 2017-08-10 21:47
I've commented on the issue. I'm not a haskell developer. so I can't really contribute to this project by code. so the only thing I can do is giving my opinion as a user/dba from that perspective.

**Comment by omani** [comment] 2017-08-14 09:45
what are your thoughts? I would love to hear from you that you will implement this. I really have a use case and am looking forward seeing this feature in the next release/and or master.

**Comment by steve-chavez** [comment] 2017-08-14 17:56
See my proposal on #328 if we all agree on the interface I could implement this feature.

**Comment by ruslantalpa** [comment] 2017-08-15 08:31
duplicate of #328

**Closed by ruslantalpa** 2017-08-15 08:31 UTC
