### ISSUE TITLE
DELETE with Prefer: 'return=minimal' always returns 404

### ISSUE THREAD

**Issue by matthewmueller** [begriffs/postgrest#760] opened 2016-12-06 07:38 UTC
Not sure if this is desired or not, but it looks like deleting items with `return=minimal`, even if it succeeds, will return a 404.

**Comment by diogob** [comment] 2017-03-16 02:11
@matthewmueller I've coded a quick spec to test this case and it returns a 204 with an empty body. Could you post a script or an endpoint to help reproduce the 404 case?

**Comment by diogob** [comment] 2017-03-20 03:32
@begriffs could not reproduce this in current master, maybe we should close it

**Closed** 2017-03-20 06:53 UTC
Labels: bug
