### ISSUE TITLE
Binary secret cannot be read from a file

### ISSUE THREAD

**Issue by eric-brechemier** [begriffs/postgrest#876] opened 2017-05-18 19:28 UTC
Using following secret made of 8 random bytes:

```
$ openssl rand 8 > /tmp/secret.bin
$ cat /tmp/secret.bin | xxd
00000000: 8ea1 d877 40be 5639                      ...w@.V9
```

```
## choose a secret to enable JWT auth
## (use "@filename" to load from separate file)
jwt-secret = "@/tmp/secret.bin"
# secret-is-base64 = false
```

PostgREST v0.4.1.0 fails with following error when the secret is read from a file:

```
postgrest: /tmp/secret.bin: hGetContents: invalid argument (invalid byte sequence)
```

**Comment by begriffs** [comment] 2017-05-30 05:29
Thanks for the report. I see there are commits referring to this issue -- do you have a PR you can send to fix it?

**Comment by begriffs** [comment] 2017-07-02 04:26
@eric-brechemier probably base64 encoding would be a workaround, but do you already have an idea of the cause of this problem?

**Comment by eric-brechemier** [comment] 2017-07-03 08:36
@begriffs Yes.

1. [secret is defined as `Text` instead of `Secret`](https://github.com/eGullGolf/postgrest/commit/2649098b5c9766e51122065e062ce1d1e3fbc28a#diff-d6621ea7eea0dc9e1ea18f49f17cdc6bL42) 
2. [secret is corrupted by the conversion to `Text`](https://github.com/eGullGolf/postgrest/commit/2649098b5c9766e51122065e062ce1d1e3fbc28a#diff-cf0c4471495584a946dc7035028102e7L95) instead of [being saved as a `binarySecret`](https://github.com/eGullGolf/postgrest/commit/0c955cb28fc6f108923cdc12066f063dc6c02998#diff-cf0c4471495584a946dc7035028102e7R96)

**Comment by ruslantalpa** [comment] 2017-09-19 15:09
4.3 has a lot of new stuff related to jwt which probably fixes this (since you can use base64 to encode it)

**Comment by eric-brechemier** [comment] 2017-09-22 14:57
@ruslantalpa I'll uncomment the unit tests and check then ;)

**Comment by eric-brechemier** [comment] 2017-09-22 17:32
@ruslantalpa the tests still fail in v0.4.3.0:

```
$ ./io-tests.sh 
1..12
ok 1 - authentication with simple (no EOL) secret read from a file
not ok 2 - failed to authenticate using JWT for simple secret: 401
ok 3 - authentication with ASCII (no EOL) secret read from a file
not ok 4 - failed to authenticate using JWT for ASCII secret: 401
ok 5 - authentication with UTF-8 (no EOL) secret read from a file
not ok 6 - failed to authenticate using JWT for UTF-8 secret: 401
postgrest: /dev/stdin: hGetContents: invalid argument (invalid byte sequence)
not ok 7 - failed to read binary secret from a file
postgrest: /dev/stdin: hGetContents: invalid argument (invalid byte sequence)
not ok 8 - failed to read binary (+EOL) secret from a file
ok 9 - authentication with Base64 (simple) secret read from a file
ok 10 - authentication with Base64 (ASCII) secret read from a file
ok 11 - authentication with Base64 (UTF-8) secret read from a file
ok 12 - authentication with Base64 (binary) secret read from a file
```
Please reopen.

**Comment by ruslantalpa** [comment] 2017-09-22 18:37
so do your tests show that the secret from file works as long as it's text/base64 and only raw binary does not work?
do we really need to support binary if binary as base64 works?

**Comment by eric-brechemier** [comment] 2017-09-22 19:57
> so do your tests show that the secret from file works as long as it's text/base64 and only raw binary does not work?

No: the failed tests number 2, 4 and 6 show that text secrets are read incorrectly when the file ends with a newline.

```
not ok 2 - failed to authenticate using JWT for simple secret: 401
not ok 4 - failed to authenticate using JWT for ASCII secret: 401
not ok 6 - failed to authenticate using JWT for UTF-8 secret: 401
```

> do we really need to support binary if binary as base64 works?

I, personally, would be fine with a requirement for secret files to be encoded in base64. If other types of encodings are allowed, there is some work left.

**Comment by ruslantalpa** [comment] 2017-09-23 18:02
for 2,4,6 i actually consider that to be the correct behaviour. The moment you start disregarding `\n` it means you have a specific file format. 
The file should contain the secret in the same way you define that secret in the postgrest.conf file, i.e. if you do not write `secret="somesecre\n"` and expect the new line to be ignored, then don't do it in the file either, i.e. everything in the file is part of the secret, the same everything between `""` is part of the secret.

for the binary format i would think base64 is enought, there is not much to be gained by supporting raw binary directly (unless it's like 1 line change)

**Comment by eric-brechemier** [comment] 2017-09-25 08:33
> for 2,4,6 i actually consider that to be the correct behaviour. The moment you start disregarding \n it means you have a specific file format.

Not really. This would go against Unix conventions:

* [Why should text files end with a newline?](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)

See also the discussion related to the end of line at the end of base64 files:
https://github.com/begriffs/postgrest/issues/877#issue-229784129

> you do not write secret="somesecre\n" and expect the new line to be ignored

Obviously not, because it is
1. visible, escaped as `\n`
2. explicit, you had to write it to put it there.

> for the binary format i would think base64 is enought, there is not much to be gained by supporting raw binary directly (unless it's like 1 line change)

I agree. Base64 alone is sufficient and less confusing than raw binary.

**Comment by eric-brechemier** [comment] 2017-09-27 12:21
I have a pull request ready: https://github.com/begriffs/postgrest/pull/988

**Comment by begriffs** [comment] 2017-09-29 02:55
Pull request is now merged!

**Closed by begriffs** 2017-09-29 02:55 UTC
